(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> dictionary update sequence element #0 has length 1; 2 is required"
p3
sS'layer'
p4
S'/home/hpiard/PycharmProjects/OXaaS_ssllabs/web2py/applications/ssllabs/controllers/tools.py'
p5
sS'code'
p6
S'@auth.requires_login()\ndef certhealth():\n    ip_addresses = db().select(db.us_ips.ALL, orderby=db.us_ips.ip_address)\n    return dict(message1="certhealth")\n\n\n@auth.requires_login()\ndef ping():\n    message2 = "Welcome!"\n    return dict(message2)\n\n\n@auth.requires_login()\ndef traceroute():\n    return dict(message3="traceroute")\n\n\n@auth.requires_login()\ndef whois():\n    return dict(message4="whois")\n\nresponse._vars=response._caller(ping)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/hpiard/PycharmProjects/OXaaS_ssllabs/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/hpiard/PycharmProjects/OXaaS_ssllabs/web2py/applications/ssllabs/controllers/tools.py", line 22, in <module>\n  File "/home/hpiard/PycharmProjects/OXaaS_ssllabs/web2py/gluon/globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/hpiard/PycharmProjects/OXaaS_ssllabs/web2py/gluon/tools.py", line 4241, in f\n    return action(*a, **b)\n  File "/home/hpiard/PycharmProjects/OXaaS_ssllabs/web2py/applications/ssllabs/controllers/tools.py", line 10, in ping\n    return dict(message2)\nValueError: dictionary update sequence element #0 has length 1; 2 is required\n'
p11
s.